openapi: 3.0.0
info:
  title: GenKiKoi API
  version: 1.0.0
  description: API documentation for GenKiKoi service

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: Authentication
    description: Auth related operations
  - name: Appointments
    description: Appointment management  
  - name: Doctors
    description: Doctor related operations
  - name: Payments
    description: Payment operations
  - name: Medical Records
    description: Medical records management

paths:
  /api/appointments:
    post:
      summary: Create new appointment
      tags: [Appointments]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - doctorId
                - scheduleId
                - appointmentType
                - symptoms
              properties:
                doctorId:
                  type: string
                scheduleId:
                  type: string
                appointmentType:
                  type: string
                  enum: [ONLINE, OFFLINE]
                symptoms:
                  type: string
                address:
                  type: string
      responses:
        '201':
          description: Appointment created successfully
        '400':
          description: Invalid request
        '500':
          description: Server error
    
    get:
      summary: Get appointments list
      tags: [Appointments]
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [PENDING, CONFIRMED, CANCELLED, COMPLETED]
        - name: role
          in: query
          schema:
            type: string
            enum: [DOCTOR, CUSTOMER]
      responses:
        '200':
          description: List of appointments
        '500':
          description: Server error

  /api/medical-records:
    post:
      summary: Create medical record
      tags: [Medical Records]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                appointmentId:
                  type: string
                diagnosis:
                  type: string
                prescription:
                  type: array
                  items:
                    type: object
                    properties:
                      medicineName:
                        type: string
                      dosage:
                        type: string
                      duration:
                        type: string
                note:
                  type: string
      responses:
        '201':
          description: Medical record created successfully
        '400':
          description: Invalid request
        '500':
          description: Server error
