export const medicines = [
  "Amoxicillin",
  "Tetracycline",
  "Oxytetracycline",
  "Chloramphenicol",
  "Erythromycin",
  "Metronidazole",
  "Methylene Blue",
  "Malachite Green",
  "Potassium Permanganate",
  "Formalin",
  "Praziquantel",
  "Levamisole",
  "Fenbendazole",
  "Dimilin",
  "Trichlorfon",
  "Copper Sulfate",
  "Acriflavine",
  "Iodine",
  "Neomycin",
  "Kanamycin",
  "Furazolidone",
  "Sulfa Drugs (Sulfadimethoxine)",
  "Nitrofurazone",
  "Ciprofloxacin",
  "Baytril (Enrofloxacin)",
  "Furan-2",
  "Melafix",
  "Pimafix",
  "Aquaflavin",
  "Betadine",
];
