name: Node.js CI

on:
  push:
    branches: 
      - main
      - develop 
      - 'feature/*' 
  pull_request:
    branches: 
      - develop 
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10 

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log before test
        run: echo "Running tests..."
      - name: Install dependencies and run tests (Server)
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          cd server
          npm ci
          npm test
      - name: Log after test
        run: echo "Tests completed, building server..."
      - name: Build server
        run: |
          cd server
          npm run build --if-present
      - name: Log after build
        run: echo "Build completed!"

